### ISSUE TITLE
Invisible Boats when player tries to move before start

### ISSUE THREAD

**Issue by nordlead2005** [TrollskogenMC/racing#41] opened 2020-03-22 01:10 UTC
I'm not exactly sure what is causing this, but when player A tries moving before the race starts player B will sometimes have an invisible boat in their client (disconnect/restart fixes it for Player B). This means that player B will crash into the boat if you are doing a circuit and cross the start line multiple times.

**Comment by hornta** [comment] 2020-03-22 12:26
I can try and take a look at this.

**Comment by hornta** [comment] 2020-03-22 12:52
I'm unable to reproduce this.

**Comment by hornta** [comment] 2020-04-17 17:19
@nordlead2005 Are you still getting this?

**Comment by hornta** [comment] 2020-05-21 20:14
Closing because not reproducible.

**Closed** 2020-05-21 20:14 UTC
